# authentication error messages
authentication.err.validation.authenticator.notfound=Authentifizierung fehlgeschlagen, Authentifizierer mit Namen {0} nicht gefunden
authentication.err.validation.authenticator.notactive=Der Authentifizierer ist nicht aktiv.

authentication.err.authentication=Authentifizierung fehlgeschlagen, Benutzername oder Passwort falsch. Benutzername: {0} Grund: {1}
authentication.err.connection=Verbindung mit {0} fehlgeschlagen. Grund: {1}
authentication.err.communication=Kommunikation mit {0} fehlgeschlagen. Grund: {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Verbindung fehlgeschlagen, LDAP-Host {0} nicht bekannt
authentication.err.connection.ldap.user.notfound=LDAP-Benutzer {0} nicht gefunden
authentication.err.connection.ldap.manager.notfound=LDAP Manager-Benutzer {0} nicht gefunden
authentication.err.connection.ldap.search=LDAP kann nicht durchsucht werden. Grund: {0}

# PASSTHRU
authentication.err.connection.passthru.server=Sitzung mit Passthru-Server konnte nicht ge\u00f6ffnet werden.
authentication.err.passthru.token.unsupported=Nicht unterst\u00fctzter Authentifizierungs-Token
authentication.err.passthru.guest.notenabled=G\u00e4ste-Anmeldungen deaktiviert
authentication.err.passthru.user.disabled=Konto deaktiviert
authentication.err.passthru.user.notfound=Passthru-Benutzer {0} nicht gefunden

# Authentication Diagnostic Steps
authentication.step.ldap.validation=\u00dcberpr\u00fcfung der Anfrage
authentication.step.ldap.connecting=Verbindungsaufbau zum LDAP-Server {0} 
authentication.step.ldap.connected=Verbunden mit LDAP-Server {0} mit Prinzipalserver {1}
authentication.step.ldap.lookup=Suche nach Testbenutzer mit Benutzer-ID {0}, Anfrage  {1}
authentication.step.ldap.lookedup=Gesucht nach Testbenutzer mit Benutzer-ID {0}, Distinguished Name (DN) gefunden: {1}
authentication.step.ldap.format.user=Format f\u00fcr Benutzername, Benutzernamenformat: {2} Format f\u00fcr Benutzer mit Benutzer-ID {0}, um folgenden Distinguished Name (DN) zu erstellen: {1}
authentication.step.ldap.authentication=Benutzer-ID authentifizieren: {0}


# Sync Summary message 
synchronization.summary.status={0} Benutzer und {1} Gruppe(n) verarbeitet


# Error messages
authentication.ldap.validation.authenticator.notfound=Authentifizierer nicht gefunden

# Synchronization Diagnostic Steps
synchronization.step.users={0} Benutzer gefunden
synchronization.step.groups={0} Gruppen gefunden
synchronization.step.users.lastsynced=Zuletzt erfolgreich synchronisierte Benutzer {0}
synchronization.step.groups.lastsynced=Zuletzt erfolgreich synchronisierte Gruppen {0}

synchronization.err.ldap.search=Fehler w\u00e4hrend der LDAP-Suche. Grund: {0}
synchronization.err.ldap.get.user.id.missing=Benutzer fehlt Attribut-DN der Benutzer-ID = {0}, attributeName = {1})
synchronization.err.ldap.get.group.id.missing=Gruppe fehlt Attribut-DN der Gruppen-ID = {0}, attributeName = {1})

synchronization.err.ldap.search.base.invalid=Ung\u00fcltige Suchbasis {0}, Grund: {1}

synchronization.err.ldap.group.member.missing.exception=Mitglied der Gruppe {0} konnte nicht \u00fcber den folgenden Distinguished Name aufgel\u00f6st werden: {1}, Grund {2});
synchronization.err.ldap.group.member.missing=Mitglied der Gruppe {0} konnte nicht \u00fcber den folgenden Distinguished Name aufgel\u00f6st werden: {1});



       



